### ISSUE TITLE
Project fails to compile in Xcode 14 on Ventura

### ISSUE THREAD

**Issue by Sajjon** [kelvin13/swift-package-factory#3]
Cool project! As a heavy SourceGen user I'm excited about this project! Good job!

The project fails to compile with Xcode 14 beta 5 on Ventura, any ideas?

<img width="1512" alt="Screenshot 2022-08-18 at 21 00 37" src="https://user-images.githubusercontent.com/864410/185473963-085fb9db-53cf-44d6-a2d8-3acbb452291f.png">

**Comment by tayloraswift** [comment]
aha, that is the glue function the plugin uses to invoke SPF. so if you know the list of filenames you want to transform you can just pass them to the `.build/release/factory` executable. you just won’t get "nice" SPM integration from the plugin.

on a broader level, this is a bug. but it should be a relatively straightforward fix just use `posix_spawn` like it asks. thanks for the report!
